### ISSUE TITLE
Login for XSS attack

### ISSUE THREAD

**Issue by Gaurang033** [gauntlt/gauntlt-demo#7]
Hi Guys, 

I didn't mean to open an issue for it, however I didn't find any forum and document where I get this information. 

Would someone please let me know how to target xss attack for the pages which requires authentication.

**Comment by apolloclark** [comment]
Easiest way, use cURL to authenticate, save the cookie into a file. Then in xsser, set the --cookie=<value> to the contents of the cookie file.

**Comment by apolloclark** [comment]
Did the approach I mentioned work for you?

**Comment by Gaurang033** [comment]
Hi I followed the alternate approach provided by Arachni of phamtomjs
driver. and it worked.

Gaurang Shah
Blog: AutomationTesting.co.in <http://automationtesting.co.in>
Mobile: +91 7387756556

**Comment by Gaurang033** [comment]
Hi,

the alternate method I used to login in arachni doesn't work with gauntlt,
so now I want to use curl, however I am not sure how to club these two
command.

Can you please provide some guideline. I am doing something like this,
however it's not working.

If I don't include " When I run `curl -ik  --data
'j_username=xxxx&j_password=xxxx'
https://10.10.10.10/webui/j_spring_security_check -c /tmp/cookie.txt" line
it works fine.

*code:*
Feature: Look for cross site scripting (xss) using arachni against a URL
Scenario: Using arachni, look for cross site scripting and verify no issues
are found

  Given "arachni" is installed
  And The default aruba timeout is 600 seconds
  When I run `curl -ik  --data 'j_username=xxxx&j_password=xxxx'
https://10.10.10.10/webui/j_spring_security_check -c /tmp/cookie.txt`
  And I launch an "arachni" attack with:
  """
  arachni --http-cookie-jar=/tmp/cookie.txt --scope-https-only
--scope-dom-depth-limit=20 --audit-links
--scope-extend-path=/root/gauntlt/paths --report-save-path=test1.afr
https://10.10.10.10/

  """
  Then the output should contain "0 issues were detected."


*Error:*

  +
      +  % Total    % Received % Xferd  Average Speed   Time    Time
Time  Current
      +                                 Dload  Upload   Total   Spent
 Left  Speed
100    36    0     0  100    36      0    117 --:--:-- --:--:-- --:--:--
117
      +[-] BrowserCluster Worker#25655100: [NoMethodError] undefined method
`master' for nil:NilClass
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser_cluster/job.rb:104:in
`save_result'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser_cluster/jobs/resource_exploration.rb:33:in
`block in run'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:76:in
`call'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:76:in
`block (3 levels) in notify_observers'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`call'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`exception_jail'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:76:in
`block (2 levels) in notify_observers'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:75:in
`each'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:75:in
`block in notify_observers'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/monitor.rb:211:in
`mon_synchronize'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:74:in
`notify_observers'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:42:in
`block (2 levels) in advertise'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:1454:in
`capture'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:1309:in
`request_handler'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in
`block (3 levels) in initialize'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`call'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`exception_jail'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in
`block (2 levels) in initialize'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/monitor.rb:211:in
`mon_synchronize'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in
`block in initialize'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:245:in
`call'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:245:in
`perform_proxy_request'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:114:in
`do_GET'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/httpproxy.rb:117:in
`proxy_service'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:217:in
`call'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:217:in
`service'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/httpserver.rb:94:in
`run'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/server.rb:294:in
`block in start_thread'
      +[-] BrowserCluster Worker#25655100:
      +[-] BrowserCluster Worker#25655100: Parent:
      +[-] BrowserCluster Worker#25655100: Arachni::BrowserCluster::Worker
      +[-] BrowserCluster Worker#25655100:
      +[-] BrowserCluster Worker#25655100: Block:
      +[-] BrowserCluster Worker#25655100: #<Proc:0x000000041a73f0@
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:76>
      +[-] BrowserCluster Worker#25655100:
      +[-] BrowserCluster Worker#25655100: Caller:
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`exception_jail'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:76:in
`block (2 levels) in notify_observers'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:75:in
`each'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:75:in
`block in notify_observers'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/monitor.rb:211:in
`mon_synchronize'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:74:in
`notify_observers'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/support/mixins/observable.rb:42:in
`block (2 levels) in advertise'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:1454:in
`capture'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:1309:in
`request_handler'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in
`block (3 levels) in initialize'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`call'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/utilities.rb:400:in
`exception_jail'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in
`block (2 levels) in initialize'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/monitor.rb:211:in
`mon_synchronize'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/browser.rb:144:in
`block in initialize'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:245:in
`call'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:245:in
`perform_proxy_request'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:114:in
`do_GET'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/httpproxy.rb:117:in
`proxy_service'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:217:in
`call'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/gems/gems/arachni-1.1/lib/arachni/http/proxy_server.rb:217:in
`service'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/httpserver.rb:94:in
`run'
      +[-] BrowserCluster Worker#25655100:
/root/gauntlt_tools/arachni-1.1-0.5.7/system/usr/lib/ruby/2.2.0/webrick/server.rb:294:in
`block in start_thread'
      +[-] BrowserCluster Worker#25655100:
--------------------------------------------------------------------------------
       (RSpec::Expectations::ExpectationNotMetError)
      test.attack:16:in `Then the output should contain "0 issues were
detected."'

Failing Scenarios:
cucumber test.attack:3 # Scenario: Using arachni, look for cross site
scripting and verify no issues are found


Gaurang Shah
Blog: AutomationTesting.co.in <http://automationtesting.co.in>
Mobile: +91 7387756556

**Comment by apolloclark** [comment]
I run a simple bash script. The first line does the login to curl, saves the Session cookie into a file, and then passes that session cookie file to any of the remaining tests. I usually save the cookie to "/tmp/cookie.txt," so that it's a static location every other gauntlt run command can access.

Archani does allow you to load a static cookie file:
http://support.arachni-scanner.com/kb/general-use/logging-in-and-maintaining-a-valid-session#from-cookie-jar

**Comment by Gaurang033** [comment]
Hi apollo, 

Thanks for the help, finally figure it out, i was missing quotes when providing login script,  Now the same phantomjs script is working fine. 

Closing the issue.
